services:
  postgres:
    image: postgres:16-alpine
    container_name: figuritas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: figuritas
    ports:
      - "5432:5432"
    volumes:
      - figuritas-db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  figuritas-db-data:
