BEGIN;

CREATE TEMP TABLE figumatch_v2 (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO figumatch_v2 (code, name, category) VALUES
('DZA 1','Escudo de Algeria','Escudo'),
('DZA 2','Alexis Guendouz','Jugador'),
('DZA 3','Ramy Bensebaini','Jugador'),
('DZA 4','Youcef Atal','Jugador'),
('DZA 5','Rayan Aït-Nouri','Jugador'),
('DZA 6','Mohamed Amine Tougai','Jugador'),
('DZA 7','Aïssa Mandi','Jugador'),
('DZA 8','Ismael Bennacer','Jugador'),
('DZA 9','Houssem Aquar','Jugador'),
('DZA 10','Hicham Boudaoui','Jugador'),
('DZA 11','Ramiz Zerrouki','Jugador'),
('DZA 12','Nabil Bentalab','Jugador'),
('DZA 13','Foto del equipo de Algeria','Equipo'),
('DZA 14','Farés Chaibi','Jugador'),
('DZA 15','Riyad Mahrez','Jugador'),
('DZA 16','Said Benrahma','Jugador'),
('DZA 17','Anis Hadj Moussa','Jugador'),
('DZA 18','Amine Gouiri','Jugador'),
('ADZ 19','Baghdad Bounedjah','Jugador'),
('DZA 20','Mohammed Amoura','Jugador'),
('ARG 1','Escudo de Argentina','Escudo'),
('ARG 2','Emiliano Martinez','Jugador'),
('ARG 3','Nahuel Molina','Jugador'),
('ARG 4','Cristian Romero','Jugador'),
('ARG 5','Nicolas Otamendi','Jugador'),
('ARG 6','Nicolas Tagliafico','Jugador'),
('ARG 7','Leonardo Balerdi','Jugador'),
('ARG 8','Enzo Fernandez','Jugador'),
('ARG 9','Alexis Mac Allister','Jugador'),
('ARG 10','Rodrigo De Paul','Jugador'),
('ARG 11','Exequiel Palacios','Jugador'),
('ARG 12','Leandro Paredes','Jugador'),
('ARG 13','Foto del equipo de Argentina','Equipo'),
('ARG 14','Nico Paz','Jugador'),
('ARG 15','Franco Mastantuono','Jugador'),
('ARG 16','Nico Gonzalez','Jugador'),
('ARG 17','Lionel Messi','Jugador'),
('ARG 18','Lautaro Martinez','Jugador'),
('ARG 19','Julian Alvarez','Jugador'),
('ARG 20','Giuliano Simeone','Jugador'),
('AUS 1','Escudo de Australia','Escudo'),
('AUS 2','Mathew Ryan','Jugador'),
('AUS 3','Joe Gauci','Jugador'),
('AUS 4','Harry Souttar','Jugador'),
('AUS 5','Alessandro Circati','Jugador'),
('AUS 6','Jordan Bos','Jugador'),
('AUS 7','Aziz Behich','Jugador'),
('AUS 8','Cameron Burgess','Jugador'),
('AUS 9','Lewis Miller','Jugador'),
('AUS 10','Milos Degenek','Jugador'),
('AUS 11','Jackson Irvine','Jugador'),
('AUS 12','Riley McGree','Jugador'),
('AUS 13','Foto del equipo de Australia','Equipo'),
('AUS 14','Aiden O''Neill','Jugador'),
('AUS 15','Connor Metcalfe','Jugador'),
('AUS 16','Patrick Yazbek','Jugador'),
('AUS 17','Craig Goodwin','Jugador'),
('AUS 18','Kusini Vengi','Jugador'),
('AUS 19','Nestory Irankunda','Jugador'),
('AUS 20','Mohamed Touré','Jugador'),
('AUT 1','Escudo de Austria','Escudo'),
('AUT 2','Alexander Schlager','Jugador'),
('AUT 3','Patrick Pentz','Jugador'),
('AUT 4','David Alaba','Jugador'),
('AUT 5','Kevin Danso','Jugador'),
('AUT 6','Philipp Lienhart','Jugador'),
('AUT 7','Stefan Posch','Jugador'),
('AUT 8','Phillipp Mwene','Jugador'),
('AUT 9','Alexander Prass','Jugador'),
('AUT 10','Xaver Schlager','Jugador'),
('AUT 11','Marcel Sabitzer','Jugador'),
('AUT 12','Konrad Laimer','Jugador'),
('AUT 13','Foto del equipo de Austria','Equipo'),
('AUT 14','Florian Grillitsch','Jugador'),
('AUT 15','Nicolas Seiwald','Jugador'),
('AUT 16','Romano Schmid','Jugador'),
('AUT 17','Patrick Wimmer','Jugador'),
('AUT 18','Christoph Baumgartner','Jugador'),
('AUT 19','Michael Gregoritsch','Jugador'),
('AUT 20','Marko Arnautović','Jugador'),
('BEL 1','Escudo de Belgium','Escudo'),
('BEL 2','Thibaut Courtois','Jugador'),
('BEL 3','Arthur Theate','Jugador'),
('BEL 4','Timothy Castagne','Jugador'),
('BEL 5','Zeno Debast','Jugador'),
('BEL 6','Brandon Mechele','Jugador'),
('BEL 7','Maxim De Cuyper','Jugador'),
('BEL 8','Thomas Meunier','Jugador'),
('BEL 9','Youri Tielemans','Jugador'),
('BEL 10','Amadou Onana','Jugador'),
('BEL 11','Nicolas Raskin','Jugador'),
('BEL 12','Alexis Saelemaekers','Jugador'),
('BEL 13','Foto del equipo de Belgium','Equipo'),
('BEL 14','Hans Vanaken','Jugador'),
('BEL 15','Kevin De Bruyne','Jugador'),
('BEL 16','Jérémy Doku','Jugador'),
('BEL 17','Charles De Ketelaere','Jugador'),
('BEL 18','Leandro Trossard','Jugador'),
('BEL 19','Loïs Openda','Jugador'),
('BEL 20','Romelu Lukaku','Jugador'),
('BIH 1','Escudo de Bosnia and Herzegovina','Escudo'),
('BIH 2','Nikola Vasilj','Jugador'),
('BIH 3','Amer Dedic','Jugador'),
('BIH 4','Sead Kolasinac','Jugador'),
('BIH 5','Tarik Muharemovic','Jugador'),
('BIH 6','Nihad Mujakic','Jugador'),
('BIH 7','Nikola Katic','Jugador'),
('BIH 8','Amir Hadziahmetovic','Jugador'),
('BIH 9','Benjamin Tahirovic','Jugador'),
('BIH 10','Armin Gigovic','Jugador'),
('BIH 11','Ivan Sunjic','Jugador'),
('BIH 12','Ivan Basic','Jugador'),
('BIH 13','Foto del equipo de Bosnia and Herzegovina','Equipo'),
('BIH 14','Dzenis Burnic','Jugador'),
('BIH 15','Esmir Bajraktarevic','Jugador'),
('BIH 16','Amar Memic','Jugador'),
('BIH 17','Ermedin Demirovic','Jugador'),
('BIH 18','Edin Dzeko','Jugador'),
('BIH 19','Samed Bazdar','Jugador'),
('BIH 20','Haris Tabakovic','Jugador'),
('BRA 1','Escudo de Brazil','Escudo'),
('BRA 2','Alisson','Jugador'),
('BRA 3','Bento','Jugador'),
('BRA 4','Marquinhos','Jugador'),
('BRA 5','Éder Militão','Jugador'),
('BRA 6','Gabriel Magalhães','Jugador'),
('BRA 7','Danilo','Jugador'),
('BRA 8','Wesley','Jugador'),
('BRA 9','Lucas Paquetá','Jugador'),
('BRA 10','Casemiro','Jugador'),
('BRA 11','Bruno Guimarães','Jugador'),
('BRA 12','Luiz Henrique','Jugador'),
('BRA 13','Foto del equipo de Brazil','Equipo'),
('BRA 14','Vinicius Júnior','Jugador'),
('BRA 15','Rodrygo','Jugador'),
('BRA 16','João Pedro','Jugador'),
('BRA 17','Matheus Cunha','Jugador'),
('BRA 18','Gabriel Martinelli','Jugador'),
('BRA 19','Raphinha','Jugador'),
('BRA 20','Estévão','Jugador'),
('CAN 1','Escudo de Canada','Escudo'),
('CAN 2','Dayne St.Clair','Jugador'),
('CAN 3','Alphonso Davies','Jugador'),
('CAN 4','Alistair Johnston','Jugador'),
('CAN 5','Samuel Adekugbe','Jugador'),
('CAN 6','Riche Larvea','Jugador'),
('CAN 7','Derek Cornelius','Jugador'),
('CAN 8','Moïse Bombito','Jugador'),
('CAN 9','Kamal Miller','Jugador'),
('CAN 10','Stephen Eustáquio','Jugador'),
('CAN 11','Ismaël Koné','Jugador'),
('CAN 12','Jonathan Osorio','Jugador'),
('CAN 13','Foto del equipo de Canada','Equipo'),
('CAN 14','Jacob Shaffelburg','Jugador'),
('CAN 15','Mathieu Choinière','Jugador'),
('CAN 16','Niko Sigur','Jugador'),
('CAN 17','Tajon Buchanan','Jugador'),
('CAN 18','Liam Millar','Jugador'),
('CAN 19','Cyle Larin','Jugador'),
('CAN 20','Jonathan David','Jugador'),
('CIV 1','Escudo de Côte d''Ivoire','Escudo'),
('CIV 2','Yahia Fofana','Jugador'),
('CIV 3','Ghislain Konan','Jugador'),
('CIV 4','Wilfried Singo','Jugador'),
('CIV 5','Odilon Kossounou','Jugador'),
('CIV 6','Evan Ndicka','Jugador'),
('CIV 7','Willy Boly','Jugador'),
('CIV 8','Emmanuel Agbadou','Jugador'),
('CIV 9','Ousmane Diomande','Jugador'),
('CIV 10','Franck Kessie','Jugador'),
('CIV 11','Seko Fofana','Jugador'),
('CIV 12','Ibrahim Sangare','Jugador'),
('CIV 13','Foto del equipo de Côte d''Ivoire','Equipo'),
('CIV 14','Jean-Philippe Gbamin','Jugador'),
('CIV 15','Amad Diallo','Jugador'),
('CIV 16','Sébastien Haller','Jugador'),
('CIV 17','Simon Adingra','Jugador'),
('CIV 18','Yan Diomande','Jugador'),
('CIV 19','Evann Guessand','Jugador'),
('CIV 20','Oumar Diakite','Jugador'),
('COD 1','Escudo de DR Congo','Escudo'),
('COD 2','Lionel Mpasi','Jugador'),
('COD 3','Aaron Wan-Bissaka','Jugador'),
('COD 4','Axel Tuanzebe','Jugador'),
('COD 5','Arthur Masuaku','Jugador'),
('COD 6','Chancel Mbemba','Jugador'),
('COD 7','Joris Kayembe','Jugador'),
('COD 8','Charles Pickel','Jugador'),
('COD 9','Ngal''ayel Mukau','Jugador'),
('COD 10','Edo Kayembe','Jugador'),
('COD 11','Samuel Moutoussamy','Jugador'),
('COD 12','Noah Sadiki','Jugador'),
('COD 13','Foto del equipo de DR Congo','Equipo'),
('COD 14','Théo Bongonda','Jugador'),
('COD 15','Meschak Elia','Jugador'),
('COD 16','Yoane Wissa','Jugador'),
('COD 17','Brian Cipenga','Jugador'),
('COD 18','Fiston Mayele','Jugador'),
('COD 19','Cédric Bakambu','Jugador'),
('COD 20','Nathanaël Mbuku','Jugador'),
('COL 1','Escudo de Colombia','Escudo'),
('COL 2','Camilo Vargas','Jugador'),
('COL 3','David Ospina','Jugador'),
('COL 4','Dávinson Sánchez','Jugador'),
('COL 5','Yerry Mina','Jugador'),
('COL 6','Daniel Munoz','Jugador'),
('COL 7','Johan Mojica','Jugador'),
('COL 8','Jhon Lucumí','Jugador'),
('COL 9','Santiago Arias','Jugador'),
('COL 10','Jefferson Lerma','Jugador'),
('COL 11','Kevin Castaño','Jugador'),
('COL 12','Richard Rios','Jugador'),
('COL 13','Foto del equipo de Colombia','Equipo'),
('COL 14','James Rodriguez','Jugador'),
('COL 15','Juan Fernando Quintero','Jugador'),
('COL 16','Jorge Carrascal','Jugador'),
('COL 17','Jon Arias','Jugador'),
('COL 18','Jhon Cordova','Jugador'),
('COL 19','Luis Suarez','Jugador'),
('COL 20','Luis Diaz','Jugador'),
('CPV 1','Escudo de Cape Verde','Escudo'),
('CPV 2','Vozinha','Jugador'),
('CPV 3','Logan Costa','Jugador'),
('CPV 4','Pico','Jugador'),
('CPV 5','Diney','Jugador'),
('CPV 6','Steven Moreira','Jugador'),
('CPV 7','Wagner Pina','Jugador'),
('CPV 8','Joao Paulo','Jugador'),
('CPV 9','Yannick Semedo','Jugador'),
('CPV 10','Kevin Pina','Jugador'),
('CPV 11','Patrick Andrade','Jugador'),
('CPV 12','Jamiro Monteiro','Jugador'),
('CPV 13','Foto del equipo de Cape Verde','Equipo'),
('CPV 14','Deroy Duarte','Jugador'),
('CPV 15','Garry Rodrigues','Jugador'),
('CPV 16','Jovane Cabral','Jugador'),
('CPV 17','Ryan Mendes','Jugador'),
('CPV 18','Dailon Livramento','Jugador'),
('CPV 19','Willy Semedo','Jugador'),
('CPV 20','Bebe','Jugador'),
('CRO 1','Escudo de Croatia','Escudo'),
('CRO 2','Dominik Livaković','Jugador'),
('CRO 3','Duje Caleta-Car','Jugador'),
('CRO 4','Josko Gvardiol','Jugador'),
('CRO 5','Josip Stanišić','Jugador'),
('CRO 6','Luka Vušković','Jugador'),
('CRO 7','Josip Sutalo','Jugador'),
('CRO 8','Kristijan Jakic','Jugador'),
('CRO 9','Luka Modrić','Jugador'),
('CRO 10','Mateo Kovacic','Jugador'),
('CRO 11','Martin Baturina','Jugador'),
('CRO 12','Lovro Majer','Jugador'),
('CRO 13','Foto del equipo de Croatia','Equipo'),
('CRO 14','Mario Pasalic','Jugador'),
('CRO 15','Petar Sucic','Jugador'),
('CRO 16','Ivan Perišić','Jugador'),
('CRO 17','Marco Pasalic','Jugador'),
('CRO 18','Ante Budimir','Jugador'),
('CRO 19','Andrej Kramarić','Jugador'),
('CRO 20','Franjo Ivanovic','Jugador'),
('CUW 1','Escudo de Curaçao','Escudo'),
('CUW 2','Eloy Room','Jugador'),
('CUW 3','Armando Obispo','Jugador'),
('CUW 4','Sherel Floranus','Jugador'),
('CUW 5','Jurien Gaari','Jugador'),
('CUW 6','Joshua Brenet','Jugador'),
('CUW 7','Roshon Van Eijma','Jugador'),
('CUW 8','Shurandy Sambo','Jugador'),
('CUW 9','Livano Comenencia','Jugador'),
('CUW 10','Godfried Roemeratoe','Jugador'),
('CUW 11','Juninho Bacuna','Jugador'),
('CUW 12','Leandro Bacuna','Jugador'),
('CUW 13','Foto del equipo de Curaçao','Equipo'),
('CUW 14','Tahith Chong','Jugador'),
('CUW 15','Kenji Gorre','Jugador'),
('CUW 16','Jearl Margaritha','Jugador'),
('CUW 17','Jurgen Locadia','Jugador'),
('CUW 18','Jeremy Antonisse','Jugador'),
('CUW 19','Gervane Kastaneer','Jugador'),
('CUW 20','Sontje Hansen','Jugador'),
('CZE 1','Escudo de Czechia','Escudo'),
('CZE 2','Matej Kovar','Jugador'),
('CZE 3','Jindrich Stanek','Jugador'),
('CZE 4','Ladislav Krejci','Jugador'),
('CZE 5','Vladimir Coufal','Jugador'),
('CZE 6','Jaroslav Zeleny','Jugador'),
('CZE 7','Tomas Holes','Jugador'),
('CZE 8','David Zima','Jugador'),
('CZE 9','Michal Sadilek','Jugador'),
('CZE 10','Lukas Provod','Jugador'),
('CZE 11','Lukas Cerv','Jugador'),
('CZE 12','Tomas Soucek','Jugador'),
('CZE 13','Foto del equipo de Czechia','Equipo'),
('CZE 14','Pavel Sulc','Jugador'),
('CZE 15','Matej Vydra','Jugador'),
('CZE 16','Vasil Kusej','Jugador'),
('CZE 17','Tomas Chory','Jugador'),
('CZE 18','Vaclav Cerny','Jugador'),
('CZE 19','Adam Hlozek','Jugador'),
('CZE 20','Patrik Schick','Jugador'),
('ECU 1','Escudo de Ecuador','Escudo'),
('ECU 2','Hernán Galíndez','Jugador'),
('ECU 3','Gonzalo Valle','Jugador'),
('ECU 4','Piero Hincapié','Jugador'),
('ECU 5','Pervis Estupiñán','Jugador'),
('ECU 6','Willian Pacho','Jugador'),
('ECU 7','Ángelo Preciado','Jugador'),
('ECU 8','Joel Ordóñez','Jugador'),
('ECU 9','Moises Caicedo','Jugador'),
('ECU 10','Alan Franco','Jugador'),
('ECU 11','Kendry Paez','Jugador'),
('ECU 12','Pedro Vite','Jugador'),
('ECU 13','Foto del equipo de Ecuador','Equipo'),
('ECU 14','John Veboah','Jugador'),
('ECU 15','Leonardo Campana','Jugador'),
('ECU 16','Gonzalo Plata','Jugador'),
('ECU 17','Nilson Angulo','Jugador'),
('ECU 18','Alan Minda','Jugador'),
('ECU 19','Kevin Rodriguez','Jugador'),
('ECU 20','Enner Valencia','Jugador'),
('EGY 1','Escudo de Egypt','Escudo'),
('EGY 2','Mohamed El Shenawy','Jugador'),
('EGY 3','Mohamed Hany','Jugador'),
('EGY 4','Mohamed Hamdy','Jugador'),
('EGY 5','Yasser Ibrahim','Jugador'),
('EGY 6','Khaled Sobhi','Jugador'),
('EGY 7','Ramy Rabia','Jugador'),
('EGY 8','Hossam Abdelmaguid','Jugador'),
('EGY 9','Ahmed Fatouh','Jugador'),
('EGY 10','Marwan Attia','Jugador'),
('EGY 11','Zizo','Jugador'),
('EGY 12','Hamdy Fathy','Jugador'),
('EGY 13','Foto del equipo de Egypt','Equipo'),
('EGY 14','Mohamed Lasheen','Jugador'),
('EGY 15','Emam Ashour','Jugador'),
('EGY 16','Osama Faisal','Jugador'),
('EGY 17','Mohamed Salah','Jugador'),
('EGY 18','Mostafa Mohamed','Jugador'),
('EGY 19','Trezeguet','Jugador'),
('EGY 20','Omar Marmoush','Jugador'),
('ENG 1','Escudo de England','Escudo'),
('ENG 2','Jordan Pickford','Jugador'),
('ENG 3','John Stones','Jugador'),
('ENG 4','Marc Guéhi','Jugador'),
('ENG 5','Ezri Konsa','Jugador'),
('ENG 6','Trent Alexander-Arnold','Jugador'),
('ENG 7','Reece James','Jugador'),
('ENG 8','Dan Burn','Jugador'),
('ENG 9','Jordan Henderson','Jugador'),
('ENG 10','Declan Rice','Jugador'),
('ENG 11','Jude Bellingham','Jugador'),
('ENG 12','Cole Palmer','Jugador'),
('ENG 13','Foto del equipo de England','Equipo'),
('ENG 14','Morgan Rogers','Jugador'),
('ENG 15','Anthony Gordon','Jugador'),
('ENG 16','Phil Foden','Jugador'),
('ENG 17','Bukayo Saka','Jugador'),
('ENG 18','Harry Kane','Jugador'),
('ENG 19','Marcus Rashford','Jugador'),
('ENG 20','Ollie Watkins','Jugador'),
('ESP 1','Escudo de Spain','Escudo'),
('ESP 2','Unai Simon','Jugador'),
('ESP 3','Robin Le Normand','Jugador'),
('ESP 4','Aymeric Laporte','Jugador'),
('ESP 5','Dean Huijsen','Jugador'),
('ESP 6','Pedro Porro','Jugador'),
('ESP 7','Dani Carvajal','Jugador'),
('ESP 8','Marc Cucurella','Jugador'),
('ESP 9','Martín Zubimendi','Jugador'),
('ESP 10','Rodri','Jugador'),
('ESP 11','Pedri','Jugador'),
('ESP 12','Fabian Ruiz','Jugador'),
('ESP 13','Foto del equipo de Spain','Equipo'),
('ESP 14','Mikel Merino','Jugador'),
('ESP 15','Lamine Yamal','Jugador'),
('ESP 16','Dani Olmo','Jugador'),
('ESP 17','Nico Williams','Jugador'),
('ESP 18','Ferran Torres','Jugador'),
('ESP 19','Álvaro Morata','Jugador'),
('ESP 20','Mikel Oyarzabal','Jugador'),
('FRA 1','Escudo de France','Escudo'),
('FRA 2','Mike Maignan','Jugador'),
('FRA 3','Theo Hernandez','Jugador'),
('FRA 4','William Saliba','Jugador'),
('FRA 5','Jules Kounde','Jugador'),
('FRA 6','Ibrahima Konate','Jugador'),
('FRA 7','Dayot Upamecano','Jugador'),
('FRA 8','Lucas Digne','Jugador'),
('FRA 9','Aurélien Tchouaméni','Jugador'),
('FRA 10','Eduardo Camavinga','Jugador'),
('FRA 11','Manu Kone','Jugador'),
('FRA 12','Adrien Rabiot','Jugador'),
('FRA 13','Foto del equipo de France','Equipo'),
('FRA 14','Michael Olise','Jugador'),
('FRA 15','Ousmane Dembele','Jugador'),
('FRA 16','Bradley Barcola','Jugador'),
('FRA 17','Désiré Doué','Jugador'),
('FRA 18','Kingsley Coman','Jugador'),
('FRA 19','Hugo Ekitike','Jugador'),
('FRA 20','Kylian Mbappe','Jugador'),
('GER 1','Escudo de Germany','Escudo'),
('GER 2','Marc-André ter Stegen','Jugador'),
('GER 3','Jonathan Tah','Jugador'),
('GER 4','David Raum','Jugador'),
('GER 5','Nico Schlotterbeck','Jugador'),
('GER 6','Antonio Rüdiger','Jugador'),
('GER 7','Waldemar Anton','Jugador'),
('GER 8','Ridle Baku','Jugador'),
('GER 9','Maximilian Mittelstadt','Jugador'),
('GER 10','Joshua Kimmich','Jugador'),
('GER 11','Florian Wirtz','Jugador'),
('GER 12','Felix Nmecha','Jugador'),
('GER 13','Foto del equipo de Germany','Equipo'),
('GER 14','Leon Goretzka','Jugador'),
('GER 15','Jamal Musiala','Jugador'),
('GER 16','Serge Gnabry','Jugador'),
('GER 17','Kai Havertz','Jugador'),
('GER 18','Leroy Sane','Jugador'),
('GER 19','Karim Adeyemi','Jugador'),
('GER 20','Nick Woltemade','Jugador'),
('GHA 1','Escudo de Ghana','Escudo'),
('GHA 2','Lawrence Ati Zigi','Jugador'),
('GHA 3','Tariq Lamptey','Jugador'),
('GHA 4','Mohammed Salisu','Jugador'),
('GHA 5','Alidu Seidu','Jugador'),
('GHA 6','Alexander Djiku','Jugador'),
('GHA 7','Gideon Mensah','Jugador'),
('GHA 8','Caleb Yirenkyi','Jugador'),
('GHA 9','Abdul Issahaku Fatawu','Jugador'),
('GHA 10','Thomas Partey','Jugador'),
('GHA 11','Salis Abdul Samed','Jugador'),
('GHA 12','Kamaldeen Sulemana','Jugador'),
('GHA 13','Foto del equipo de Ghana','Equipo'),
('GHA 14','Mohammed Kudus','Jugador'),
('GHA 15','Inaki Williams','Jugador'),
('GHA 16','Jordan Ayew','Jugador'),
('GHA 17','Andrew Ayew','Jugador'),
('GHA 18','Joseph Paintsil','Jugador'),
('GHA 19','Osman Bukari','Jugador'),
('GHA 20','Antoine Semenyo','Jugador'),
('HAI 1','Escudo de Haiti','Escudo'),
('HAI 2','Johny Placide','Jugador'),
('HAI 3','Carlens Arcus','Jugador'),
('HAI 4','Martin Expérience','Jugador'),
('HAI 5','Jean-Kevin Duverne','Jugador'),
('HAI 6','Ricardo Adé','Jugador'),
('HAI 7','Duke Lacroix','Jugador'),
('HAI 8','Garven Metusala','Jugador'),
('HAI 9','Hannes Delcroix','Jugador'),
('HAI 10','Leverton Pierre','Jugador'),
('HAI 11','Danley Jean Jacques','Jugador'),
('HAI 12','Jean-Ricner Bellegarde','Jugador'),
('HAI 13','Foto del equipo de Haiti','Equipo'),
('HAI 14','Christopher Attys','Jugador'),
('HAI 15','Derrick Etienne Jr','Jugador'),
('HAI 16','Josue Casimir','Jugador'),
('HAI 17','Ruben Providence','Jugador'),
('HAI 18','Duckens Nazon','Jugador'),
('HAI 19','Louicius Deedson','Jugador'),
('HAI 20','Frantzdy Pierrot','Jugador'),
('IRN 1','Escudo de Iran','Escudo'),
('IRN 2','Alireza Beiranvand','Jugador'),
('IRN 3','Morteza Pouraliganji','Jugador'),
('IRN 4','Ehsan Hajsafi','Jugador'),
('IRN 5','Milad Mohammadi','Jugador'),
('IRN 6','Shojae Khalilzadeh','Jugador'),
('IRN 7','Ramin Rezaeian','Jugador'),
('IRN 8','Hossein Kanaani','Jugador'),
('IRN 9','Sadegh Moharrami','Jugador'),
('IRN 10','Saleh Hardani','Jugador'),
('IRN 11','Saeed Ezatolahi','Jugador'),
('IRN 12','Saman Ghoddos','Jugador'),
('IRN 13','Foto del equipo de Iran','Equipo'),
('IRN 14','Omid Noorafkan','Jugador'),
('IRN 15','Roozbeh Cheshmi','Jugador'),
('IRN 16','Mohammad Mohebi','Jugador'),
('IRN 17','Sardar Azmoun','Jugador'),
('IRN 18','Mehdi Taremi','Jugador'),
('IRN 19','Alireza Jahanbakhsh','Jugador'),
('IRN 20','Ali Gholizadeh','Jugador'),
('IRQ 1','Escudo de Iraq','Escudo'),
('IRQ 2','Jalal Hassan','Jugador'),
('IRQ 3','Rebin Sulaka','Jugador'),
('IRQ 4','Hussein Ali','Jugador'),
('IRQ 5','Akam Hashem','Jugador'),
('IRQ 6','Merchas Doski','Jugador'),
('IRQ 7','Zaid Tahseen','Jugador'),
('IRQ 8','Manaf Younis','Jugador'),
('IRQ 9','Zidane Iqbal','Jugador'),
('IRQ 10','Amir Al-Ammari','Jugador'),
('IRQ 11','Ibrahim Bavesh','Jugador'),
('IRQ 12','Ali Jasim','Jugador'),
('IRQ 13','Foto del equipo de Iraq','Equipo'),
('IRQ 14','Youssef Amyn','Jugador'),
('IRQ 15','Aimar Sher','Jugador'),
('IRQ 16','Marko Farji','Jugador'),
('IRQ 17','Osama Rashid','Jugador'),
('IRQ 18','Ali Al-Hamadi','Jugador'),
('IRQ 19','Aymen Hussein','Jugador'),
('IRQ 20','Mohanad Ali','Jugador'),
('JOR 1','Escudo de Jordan','Escudo'),
('JOR 2','Yazeed Abulaila','Jugador'),
('JOR 3','Ihsan Haddad','Jugador'),
('JOR 4','Mohammad Abu Hashish','Jugador'),
('JOR 5','Yazan Al-Arab','Jugador'),
('JOR 6','Abdallah Nasib','Jugador'),
('JOR 7','Saleem Obaid','Jugador'),
('JOR 8','Mohammad Abualnadi','Jugador'),
('JOR 9','Ibrahim Saadeh','Jugador'),
('JOR 10','Nizar Al-Rashdan','Jugador'),
('JOR 11','Noor Al-Rawabdeh','Jugador'),
('JOR 12','Mohannad Abu Taha','Jugador'),
('JOR 13','Foto del equipo de Jordan','Equipo'),
('JOR 14','Amer Jamous','Jugador'),
('JOR 15','Musa Al-Taamari','Jugador'),
('JOR 16','Yazan Al-Naimat','Jugador'),
('JOR 17','Mahmoud Al-Mardi','Jugador'),
('JOR 18','Ali Olwan','Jugador'),
('JOR 19','Mohammad Abu Zrayq','Jugador'),
('JOR 20','Ibrahim Sabra','Jugador'),
('JPN 1','Escudo de Japan','Escudo'),
('JPN 2','Zion Suzuki','Jugador'),
('JPN 3','Henry Heroki Mochizuki','Jugador'),
('JPN 4','Ayumu Seko','Jugador'),
('JPN 5','Junnosuke Suzuki','Jugador'),
('JPN 6','Shogo Taniguchi','Jugador'),
('JPN 7','Tsuyoshi Watanabe','Jugador'),
('JPN 8','Kaishu Sano','Jugador'),
('JPN 9','Yuki Soma','Jugador'),
('JPN 10','Ao Tanaka','Jugador'),
('JPN 11','Daichi Kamada','Jugador'),
('JPN 12','Takefusa Kubo','Jugador'),
('JPN 13','Foto del equipo de Japan','Equipo'),
('JPN 14','Ritsu Doan','Jugador'),
('JPN 15','Keito Nakamura','Jugador'),
('JPN 16','Takumi Minamino','Jugador'),
('JPN 17','Shuto Machino','Jugador'),
('JPN 18','Junya Ito','Jugador'),
('JPN 19','Koki Ogawa','Jugador'),
('JPN 20','Ayase Ueda','Jugador'),
('KOR 1','Escudo de South Korea','Escudo'),
('KOR 2','Hyeon-woo Jo','Jugador'),
('KOR 3','Seung-Gyu Kim','Jugador'),
('KOR 4','Min-jae Kim','Jugador'),
('KOR 5','Yu-min Cho','Jugador'),
('KOR 6','Young-woo Seol','Jugador'),
('KOR 7','Han-beom Lee','Jugador'),
('KOR 8','Tae-seok Lee','Jugador'),
('KOR 9','Myung-jae Lee','Jugador'),
('KOR 10','Jae-sung Lee','Jugador'),
('KOR 11','In-beom Hwang','Jugador'),
('KOR 12','Kang-in Lee','Jugador'),
('KOR 13','Foto del equipo de South Korea','Equipo'),
('KOR 14','Seung-ho Paik','Jugador'),
('KOR 15','Jens Castrop','Jugador'),
('KOR 16','Dongg-yeong Lee','Jugador'),
('KOR 17','Gue-sung Cho','Jugador'),
('KOR 18','Heung-min Son','Jugador'),
('KOR 19','Hee-chan Hwang','Jugador'),
('KOR 20','Hyeon-Gyu Oh','Jugador'),
('KSA 1','Escudo de Saudi Arabia','Escudo'),
('KSA 2','Nawaf Alaqidi','Jugador'),
('KSA 3','Abdulrahman Al-Sanbi','Jugador'),
('KSA 4','Saud Abdulhamid','Jugador'),
('KSA 5','Nawaf Bouwashl','Jugador'),
('KSA 6','Jihad Thakri','Jugador'),
('KSA 7','Moteb Al-Harbi','Jugador'),
('KSA 8','Hassan Altambakti','Jugador'),
('KSA 9','Musab Aljuwayr','Jugador'),
('KSA 10','Ziyad Aljohani','Jugador'),
('KSA 11','Abdullah Alkhaibari','Jugador'),
('KSA 12','Nasser Aldawsari','Jugador'),
('KSA 13','Foto del equipo de Saudi Arabia','Equipo'),
('KSA 14','Saleh Abu Alshamat','Jugador'),
('KSA 15','Marwan Alsahafi','Jugador'),
('KSA 16','Salem Aldawsari','Jugador'),
('KSA 17','Abdulrahman Al-Aboud','Jugador'),
('KSA 18','Feras Akbrikan','Jugador'),
('KSA 19','Saleh Alshehri','Jugador'),
('KSA 20','Abdullah Al-Hamdan','Jugador'),
('MAR 1','Escudo de Morocco','Escudo'),
('MAR 2','Yassine Bounou','Jugador'),
('MAR 3','Munir El Kajoui','Jugador'),
('MAR 4','Achraf Hakimi','Jugador'),
('MAR 5','Noussair Mazraoui','Jugador'),
('MAR 6','Nayef Aguerd','Jugador'),
('MAR 7','Roman Saiss','Jugador'),
('MAR 8','Jawad El Yamio','Jugador'),
('MAR 9','Adam Masina','Jugador'),
('MAR 10','Sofyan Amrabat','Jugador'),
('MAR 11','Azzedine Ounahi','Jugador'),
('MAR 12','Eliesse Ben Seghir','Jugador'),
('MAR 13','Foto del equipo de Morocco','Equipo'),
('MAR 14','Bilal El Khannouss','Jugador'),
('MAR 15','Ismael Saibari','Jugador'),
('MAR 16','Youssef En-Nesyri','Jugador'),
('MAR 17','Abde Ezzalzouli','Jugador'),
('MAR 18','Soufiane Rahimi','Jugador'),
('MAR 19','Brahim Diaz','Jugador'),
('MAR 20','Ayoub El Kaabi','Jugador'),
('MEX 1','Escudo de Mexico','Escudo'),
('MEX 2','Luis Malagón','Jugador'),
('MEX 3','Johan Vasquez','Jugador'),
('MEX 4','Jorge Sánchez','Jugador'),
('MEX 5','Cesar Montes','Jugador'),
('MEX 6','Jesus Gallardo','Jugador'),
('MEX 7','Israel Reyes','Jugador'),
('MEX 8','Diego Lainez','Jugador'),
('MEX 9','Carlos Rodriguez','Jugador'),
('MEX 10','Edson Alvarez','Jugador'),
('MEX 11','Orbelin Pineda','Jugador'),
('MEX 12','Marcel Ruiz','Jugador'),
('MEX 13','Foto del equipo de Mexico','Equipo'),
('MEX 14','Érick Sánchez','Jugador'),
('MEX 15','Hirving Lozano','Jugador'),
('MEX 16','Santiago Giménez','Jugador'),
('MEX 17','Raúl Jiménez','Jugador'),
('MEX 18','Alexis Vega','Jugador'),
('MEX 19','Roberto Alvarado','Jugador'),
('MEX 20','Cesar Huerta','Jugador'),
('NED 1','Escudo de Netherlands','Escudo'),
('NED 2','Bart Verbruggen','Jugador'),
('NED 3','Virgil van Dijk','Jugador'),
('NED 4','Micky van de Ven','Jugador'),
('NED 5','Jurrien Timber','Jugador'),
('NED 6','Denzel Dumfries','Jugador'),
('NED 7','Nathan Aké','Jugador'),
('NED 8','Jeremie Frimpong','Jugador'),
('NED 9','Jan Paul van Hecke','Jugador'),
('NED 10','Tijjani Reijnders','Jugador'),
('NED 11','Ryan Gravenberch','Jugador'),
('NED 12','Teun Koopmeiners','Jugador'),
('NED 13','Foto del equipo de Netherlands','Equipo'),
('NED 14','Frenkie de Jong','Jugador'),
('NED 15','Xavi Simons','Jugador'),
('NED 16','Justin Kluivert','Jugador'),
('NED 17','Memphis Depay','Jugador'),
('NED 18','Donyell Malen','Jugador'),
('NED 19','Wout Weghorst','Jugador'),
('NED 20','Cody Gakpo','Jugador'),
('NOR 1','Escudo de Norway','Escudo'),
('NOR 2','Orjan Nyland','Jugador'),
('NOR 3','Julian Ryerson','Jugador'),
('NOR 4','Leo Ostigård','Jugador'),
('NOR 5','Kristoffer Vassbakk Ajer','Jugador'),
('NOR 6','Marcus Holmgren Pedersen','Jugador'),
('NOR 7','David Møller Wolfe','Jugador'),
('NOR 8','Torbjørn Heggem','Jugador'),
('NOR 9','Morten Thorsby','Jugador'),
('NOR 10','Martin Ødegaard','Jugador'),
('NOR 11','Sander Berge','Jugador'),
('NOR 12','Andreas Schjelderup','Jugador'),
('NOR 13','Foto del equipo de Norway','Equipo'),
('NOR 14','Patrick Berg','Jugador'),
('NOR 15','Erling Haaland','Jugador'),
('NOR 16','Alexander Sørloth','Jugador'),
('NOR 17','Aron Dønnum','Jugador'),
('NOR 18','Jorgen Strand Larsen','Jugador'),
('NOR 19','Antonio Nusa','Jugador'),
('NOR 20','Oscar Bobb','Jugador'),
('NZL 1','Escudo de New Zealand','Escudo'),
('NZL 2','Max Crocombe Payne','Jugador'),
('NZL 3','Alex Paulsen','Jugador'),
('NZL 4','Michael Boxall','Jugador'),
('NZL 5','Liberato Cacace','Jugador'),
('NZL 6','Tim Payne','Jugador'),
('NZL 7','Tyler Bindon','Jugador'),
('NZL 8','Francis de Vries','Jugador'),
('NZL 9','Finn Surman','Jugador'),
('NZL 10','Joe Bell','Jugador'),
('NZL 11','Sarpreet Singh','Jugador'),
('NZL 12','Ryan Thomas','Jugador'),
('NZL 13','Foto del equipo de New Zealand','Equipo'),
('NZL 14','Matthew Garbett','Jugador'),
('NZL 15','Marko Stamenić','Jugador'),
('NZL 16','Ben Old','Jugador'),
('NZL 17','Chris Wood','Jugador'),
('NZL 18','Elijah Just','Jugador'),
('NZL 19','Callum McCowatt','Jugador'),
('NZL 20','Kosta Barbarouses','Jugador'),
('PAN 1','Escudo de Panama','Escudo'),
('PAN 2','Orlando Mosquera','Jugador'),
('PAN 3','Luis Mejia','Jugador'),
('PAN 4','Fidel Escobar','Jugador'),
('PAN 5','Andres Andrade','Jugador'),
('PAN 6','Michael Amir Murillo','Jugador'),
('PAN 7','Eric Davis','Jugador'),
('PAN 8','Jose Cordoba','Jugador'),
('PAN 9','Cesar Blackman','Jugador'),
('PAN 10','Cristian Martinez','Jugador'),
('PAN 11','Aníbal Godoy','Jugador'),
('PAN 12','Adalberto Carrasquilla','Jugador'),
('PAN 13','Foto del equipo de Panama','Equipo'),
('PAN 14','Édgar Bárcenas','Jugador'),
('PAN 15','Carlos Harvey','Jugador'),
('PAN 16','Ismael Díaz','Jugador'),
('PAN 17','Jose Fajardo','Jugador'),
('PAN 18','Cecilio Waterman','Jugador'),
('PAN 19','Jose Luiz Rodriguez','Jugador'),
('PAN 20','Alberto Quintero','Jugador'),
('PAR 1','Escudo de Paraguay','Escudo'),
('PAR 2','Roberto Fernandez','Jugador'),
('PAR 3','Orlando Gill','Jugador'),
('PAR 4','Gustavo Gomez','Jugador'),
('PAR 5','Fabián Balbuena','Jugador'),
('PAR 6','Juan José Cáceres','Jugador'),
('PAR 7','Omar Alderete','Jugador'),
('PAR 8','Junior Alonso','Jugador'),
('PAR 9','Mathías Villasanti','Jugador'),
('PAR 10','Diego Gomez','Jugador'),
('PAR 11','Damián Bobadilla','Jugador'),
('PAR 12','Andres Cubas','Jugador'),
('PAR 13','Foto del equipo de Paraguay','Equipo'),
('PAR 14','Matias Galarza Fonda','Jugador'),
('PAR 15','Julio Enciso','Jugador'),
('PAR 16','Alejandro Romero Gamarra','Jugador'),
('PAR 17','Miguel Almirón','Jugador'),
('PAR 18','Ramon Sosa','Jugador'),
('PAR 19','Angel Romero','Jugador'),
('PAR 20','Antonio Sanabria','Jugador'),
('POR 1','Escudo de Portugal','Escudo'),
('POR 2','Diogo Costa','Jugador'),
('POR 3','Jose Sa','Jugador'),
('POR 4','Ruben Dias','Jugador'),
('POR 5','João Cancelo','Jugador'),
('POR 6','Diogo Dalot','Jugador'),
('POR 7','Nuno Mendes','Jugador'),
('POR 8','Gonçalo Inácio','Jugador'),
('POR 9','Bernardo Silva','Jugador'),
('POR 10','Bruno Fernandes','Jugador'),
('POR 11','Ruben Neves','Jugador'),
('POR 12','Vitinha','Jugador'),
('POR 13','Foto del equipo de Portugal','Equipo'),
('POR 14','João Neves','Jugador'),
('POR 15','Cristiano Ronaldo','Jugador'),
('POR 16','Francisco Trincao','Jugador'),
('POR 17','João Felix','Jugador'),
('POR 18','Gonçalo Ramos','Jugador'),
('POR 19','Pedro Neto','Jugador'),
('POR 20','Rafael Leão','Jugador'),
('QAT 1','Escudo de Qatar','Escudo'),
('QAT 2','Meshaal Barsham','Jugador'),
('QAT 3','Sultan Albrake','Jugador'),
('QAT 4','Lucas Mendes','Jugador'),
('QAT 5','Homam Ahmed','Jugador'),
('QAT 6','Boualem Khoukhi','Jugador'),
('QAT 7','Pedro Miguel','Jugador'),
('QAT 8','Tarek Salman','Jugador'),
('QAT 9','Mohamed Al-Mannai','Jugador'),
('QAT 10','Karim Boudiaf','Jugador'),
('QAT 11','Assim Madibo','Jugador'),
('QAT 12','Ahmed Fatehi','Jugador'),
('QAT 13','Foto del equipo de Qatar','Equipo'),
('QAT 14','Mohammed Waad','Jugador'),
('QAT 15','Abdulaziz Hatem','Jugador'),
('QAT 16','Hassan Al-Haydos','Jugador'),
('QAT 17','Edmilson Junior','Jugador'),
('QAT 18','Akram Hassan Afif','Jugador'),
('QAT 19','Ahmed Al Ganehi','Jugador'),
('QAT 20','Almoez Ali','Jugador'),
('RSA 1','Escudo de South Africa','Escudo'),
('RSA 2','Ronwen Williams','Jugador'),
('RSA 3','Sipho Chaine','Jugador'),
('RSA 4','Aubrey Modiba','Jugador'),
('RSA 5','Samukele Kabini','Jugador'),
('RSA 6','Mbekezeli Mbokazi','Jugador'),
('RSA 7','Khulumani Ndamane','Jugador'),
('RSA 8','Siyabonga Ngezana','Jugador'),
('RSA 9','Khuliso Mudau','Jugador'),
('RSA 10','Nkosinathi Sibisi','Jugador'),
('RSA 11','Teboho Mokoena','Jugador'),
('RSA 12','Thalente Mbatha','Jugador'),
('RSA 13','Foto del equipo de South Africa','Equipo'),
('RSA 14','Bathasi Aubaas','Jugador'),
('RSA 15','Yaya Sithole','Jugador'),
('RSA 16','Sipho Mbule','Jugador'),
('RSA 17','Lyle Foster','Jugador'),
('RSA 18','Iqraam Rayners','Jugador'),
('RSA 19','Mohau Nkota','Jugador'),
('RSA 20','Oswin Appollis','Jugador'),
('SCO 1','Escudo de Scotland','Escudo'),
('SCO 2','Angus Gunn','Jugador'),
('SCO 3','Jack Hendry','Jugador'),
('SCO 4','Kieran Tierney','Jugador'),
('SCO 5','Aaron Hickey','Jugador'),
('SCO 6','Andrew Robertson','Jugador'),
('SCO 7','Scott McKenna','Jugador'),
('SCO 8','John Souttar','Jugador'),
('SCO 9','Anthony Ralston','Jugador'),
('SCO 10','Grant Hanley','Jugador'),
('SCO 11','Scott McTominay','Jugador'),
('SCO 12','Billy Gilmour','Jugador'),
('SCO 13','Foto del equipo de Scotland','Equipo'),
('SCO 14','Lewis Ferguson','Jugador'),
('SCO 15','Ryan Christie','Jugador'),
('SCO 16','Kenny McLean','Jugador'),
('SCO 17','John McGinn','Jugador'),
('SCO 18','Lyndon Dykes','Jugador'),
('SCO 19','Che Adams','Jugador'),
('SCO 20','Ben Gannon-Doak','Jugador'),
('SEN 1','Escudo de Senegal','Escudo'),
('SEN 2','Edouard Mendy','Jugador'),
('SEN 3','Yehvann Diouf','Jugador'),
('SEN 4','Moussa Niakhaté','Jugador'),
('SEN 5','Abdoulaye Seck','Jugador'),
('SEN 6','Ismail Jakobs','Jugador'),
('SEN 7','El Hadji Malick Diouf','Jugador'),
('SEN 8','Kalidou Koulibaly','Jugador'),
('SEN 9','Idrissa Gana Gueye','Jugador'),
('SEN 10','Pape Matar Sarr','Jugador'),
('SEN 11','Pape Gueye','Jugador'),
('SEN 12','Habib Diarra','Jugador'),
('SEN 13','Foto del equipo de Senegal','Equipo'),
('SEN 14','Lamine Camara','Jugador'),
('SEN 15','Sadio Mane','Jugador'),
('SEN 16','Ismaïla Sarr','Jugador'),
('SEN 17','Boulaye Dia','Jugador'),
('SEN 18','Iliman Ndiaye','Jugador'),
('SEN 19','Nicolas Jackson','Jugador'),
('SEN 20','Krepin Diatta','Jugador'),
('SUI 1','Escudo de Switzerland','Escudo'),
('SUI 2','Gregor Kobel','Jugador'),
('SUI 3','Yvon Mvogo','Jugador'),
('SUI 4','Manuel Akanji','Jugador'),
('SUI 5','Ricardo Rodriguez','Jugador'),
('SUI 6','Nico Elvedi','Jugador'),
('SUI 7','Aurèle Amenda','Jugador'),
('SUI 8','Silvan Widmer','Jugador'),
('SUI 9','Granit Xhaka','Jugador'),
('SUI 10','Denis Zakaria','Jugador'),
('SUI 11','Remo Freuler','Jugador'),
('SUI 12','Fabian Rieder','Jugador'),
('SUI 13','Foto del equipo de Switzerland','Equipo'),
('SUI 14','Ardon Jashari','Jugador'),
('SUI 15','Johan Manzambi','Jugador'),
('SUI 16','Michel Aebischer','Jugador'),
('SUI 17','Breel Embolo','Jugador'),
('SUI 18','Ruben Vargas','Jugador'),
('SUI 19','Dan Ndoye','Jugador'),
('SUI 20','Zeki Amdouni','Jugador'),
('SWE 1','Escudo de Sweden','Escudo'),
('SWE 2','Victor Johansson','Jugador'),
('SWE 3','Isak Hien','Jugador'),
('SWE 4','Gabriel Gudmundsson','Jugador'),
('SWE 5','Emil Holm','Jugador'),
('SWE 6','Victor Nilsson Lindelöf','Jugador'),
('SWE 7','Gustaf Lagerbielke','Jugador'),
('SWE 8','Lucas Bergvall','Jugador'),
('SWE 9','Hugo Larsson','Jugador'),
('SWE 10','Jesper Karlström','Jugador'),
('SWE 11','Yasin Ayari','Jugador'),
('SWE 12','Mattias Svanberg','Jugador'),
('SWE 13','Foto del equipo de Sweden','Equipo'),
('SWE 14','Daniel Svensson','Jugador'),
('SWE 15','Ken Sema','Jugador'),
('SWE 16','Roony Bardghji','Jugador'),
('SWE 17','Dejan Kulusevski','Jugador'),
('SWE 18','Anthony Elanga','Jugador'),
('SWE 19','Alexander Isak','Jugador'),
('SWE 20','Viktor Gyökeres','Jugador'),
('TUN 1','Escudo de Tunisia','Escudo'),
('TUN 2','Bechir Ben Said','Jugador'),
('TUN 3','Aymen Dahmen','Jugador'),
('TUN 4','Yan Valery','Jugador'),
('TUN 5','Montassar Talbi','Jugador'),
('TUN 6','Yassine Meriah','Jugador'),
('TUN 7','Ali Abdi','Jugador'),
('TUN 8','Dylan Bronn','Jugador'),
('TUN 9','Ellyes Skhiri','Jugador'),
('TUN 10','Aissa Laidouni','Jugador'),
('TUN 11','Ferjani Sassi','Jugador'),
('TUN 12','Mohamed Ali Ben Romdhane','Jugador'),
('TUN 13','Foto del equipo de Tunisia','Equipo'),
('TUN 14','Hannibal Mejbri','Jugador'),
('TUN 15','Elias Achouri','Jugador'),
('TUN 16','Elias Saad','Jugador'),
('TUN 17','Hazem Mastouri','Jugador'),
('TUN 18','Ismael Gharbi','Jugador'),
('TUN 19','Sayfallah Ltaief','Jugador'),
('TUN 20','Naim Sliti','Jugador'),
('TUR 1','Escudo de Turkey','Escudo'),
('TUR 2','Ugurcan Cakir','Jugador'),
('TUR 3','Mert Muldur','Jugador'),
('TUR 4','Zeki Celik','Jugador'),
('TUR 5','Abdulkerim Bardakci','Jugador'),
('TUR 6','Caglar Soyuncu','Jugador'),
('TUR 7','Merih Demiral','Jugador'),
('TUR 8','Ferdi Kadioglu','Jugador'),
('TUR 9','Kaan Ayhan','Jugador'),
('TUR 10','Ismail Yuksek','Jugador'),
('TUR 11','Hakan Calhanoglu','Jugador'),
('TUR 12','Orkun Kokcu','Jugador'),
('TUR 13','Foto del equipo de Turkey','Equipo'),
('TUR 14','Arda Guler','Jugador'),
('TUR 15','Irfan Can Kahveci','Jugador'),
('TUR 16','Yunus Akgun','Jugador'),
('TUR 17','Can Uzun','Jugador'),
('TUR 18','Baris Alper Yilmaz','Jugador'),
('TUR 19','Kerem Akturkoglu','Jugador'),
('TUR 20','Kenan Yildiz','Jugador'),
('URU 1','Escudo de Uruguay','Escudo'),
('URU 2','Sergio Rochet','Jugador'),
('URU 3','Santiago Mele','Jugador'),
('URU 4','Ronald Araujo','Jugador'),
('URU 5','José María Giménez','Jugador'),
('URU 6','Sebastian Caceres','Jugador'),
('URU 7','Mathias Olivera','Jugador'),
('URU 8','Guillermo Varela','Jugador'),
('URU 9','Nahitan Nandez','Jugador'),
('URU 10','Federico Valverde','Jugador'),
('URU 11','Giorgian De Arrascaeta','Jugador'),
('URU 12','Rodrigo Bentancur','Jugador'),
('URU 13','Foto del equipo de Uruguay','Equipo'),
('URU 14','Manuel Ugarte','Jugador'),
('URU 15','Nicolás de la Cruz','Jugador'),
('URU 16','Maxi Araujo','Jugador'),
('URU 17','Darwin Núñez','Jugador'),
('URU 18','Federico Viñas','Jugador'),
('URU 19','Rodrigo Aguirre','Jugador'),
('URU 20','Facundo Pellistri','Jugador'),
('USA 1','Escudo de United States','Escudo'),
('USA 2','Math Freese','Jugador'),
('USA 3','Chris Richards','Jugador'),
('USA 4','Tim Ream','Jugador'),
('USA 5','Mark McKenzie','Jugador'),
('USA 6','Alex Freeman','Jugador'),
('USA 7','Antonee Robinson','Jugador'),
('USA 8','Tyler Adams','Jugador'),
('USA 9','Tanner Tessmann','Jugador'),
('USA 10','Weston McKenny','Jugador'),
('USA 11','Christian Roldan','Jugador'),
('USA 12','Timothy Weah','Jugador'),
('USA 13','Foto del equipo de United States','Equipo'),
('USA 14','Diego Luna','Jugador'),
('USA 15','Malik Tillman','Jugador'),
('USA 16','Christian Pulisic','Jugador'),
('USA 17','Brenden Aaronson','Jugador'),
('USA 18','Ricardo Pepi','Jugador'),
('USA 19','Haji Wright','Jugador'),
('USA 20','Folarin Balogun','Jugador'),
('UZB 1','Escudo de Uzbekistan','Escudo'),
('UZB 2','Utkir Yusupov','Jugador'),
('UZB 3','Farrukh Savfiev','Jugador'),
('UZB 4','Sherzod Nasrullaev','Jugador'),
('UZB 5','Umar Eshmurodov','Jugador'),
('UZB 6','Husniddin Aliqulov','Jugador'),
('UZB 7','Rustamjon Ashurmatov','Jugador'),
('UZB 8','Khojiakbar Alijonov','Jugador'),
('UZB 9','Abdukodir Khusanov','Jugador'),
('UZB 10','Odiljon Hamrobekov','Jugador'),
('UZB 11','Otabek Shukurov','Jugador'),
('UZB 12','Jamshid Iskanderov','Jugador'),
('UZB 13','Foto del equipo de Uzbekistan','Equipo'),
('UZB 14','Azizbek Turgunboev','Jugador'),
('UZB 15','Khojimat Erkinov','Jugador'),
('UZB 16','Eldor Shomurodov','Jugador'),
('UZB 17','Oston Urunov','Jugador'),
('UZB 18','Jaloliddin Masharipov','Jugador'),
('UZB 19','Igor Sergeev','Jugador'),
('UZB 20','Abbosbek Fayzullaev','Jugador');

DO $$
DECLARE c INTEGER;
BEGIN
  SELECT COUNT(*) INTO c FROM figumatch_v2;
  IF c <> 960 THEN
    RAISE EXCEPTION 'Se esperaban 960 registros y hay %', c;
  END IF;
END $$;

UPDATE stickers s
SET name = f.name,
    category = f.category
FROM figumatch_v2 f
WHERE UPPER(TRIM(s.code)) = f.code;

COMMIT;

SELECT COUNT(*) AS nombres_pendientes
FROM stickers
WHERE name IS NULL
   OR TRIM(name) = ''
   OR UPPER(TRIM(name)) = UPPER(TRIM(code));
